spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://postgres-sql:5432/demo_db
    driverClassName: org.postgresql.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 9090

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG

